import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins} from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import AuthWrapper from "./components/AuthWrapper";
import Gleap from 'gleap';
import GleapComponent from "./components/GleapComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.jpeg" />
      </head>
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          <AuthWrapper>
            {/* <main className="pt-20 bg-gray-100">
            </main> */}
              {children}
          </AuthWrapper>
        </Providers>
        <GleapComponent />
      </body>
    </html>
  );
}
